# Generated by Django 4.0.5 on 2023-01-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplina', models.CharField(choices=[('Língua Portugesa', 'Língua Portugesa'), ('Matemática', 'Matemática'), ('História', 'História'), ('Geografia', 'Geografia'), ('Biologia', 'Biologia'), ('Química', 'Química'), ('Física', 'Física'), ('Filosofia', 'Filosofia'), ('Sociologia', 'Sociologia'), ('Língua Inglesa', 'Língua Inglesa'), ('Artes', 'Artes')], max_length=20)),
                ('area', models.CharField(choices=[('Ciências Exatas e da Terra', 'Ciências Exatas e da Terra'), ('Ciências Biológicas', 'Ciências Biológicas'), ('Ciências Humanas', 'Ciências Humanas'), ('Engenharias', 'Engenharias'), ('Ciências da Saúde', 'Ciências da Saúde'), ('Ciências Agrárias', 'Ciências Agrárias'), ('Linguística, Letras e Artes', 'Linguística, Letras e Artes'), ('Ciências Sociais e Aplicadas', 'Ciências Sociais e Aplicadas')], max_length=40)),
                ('formacao', models.CharField(choices=[('Graduação', 'Graduação'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-doutorado', 'Pós-doutorado')], max_length=20)),
            ],
        ),
    ]
